export const dnd5eData = {
  races: [
    "Dragonborn",
    "Dwarf",
    "Elf",
    "Gnome",
    "Half-Elf",
    "Half-Orc",
    "Halfling",
    "Human",
    "Tiefling",
  ],
  subraces: {
    Dwarf: ["Hill Dwarf", "Mountain Dwarf"],
    Elf: ["High Elf", "Wood Elf", "Dark Elf (Drow)"],
    Gnome: ["Forest Gnome", "Rock Gnome"],
    Halfling: ["Lightfoot", "Stout"],
    Dragonborn: ["Black", "Blue", "Brass", "Bronze", "Copper", "Gold", "Green", "Red", "Silver", "White"],
  },
  classes: [
    "Barbarian",
    "Bard",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard",
  ],
  backgrounds: [
    "Acolyte",
    "Charlatan",
    "Criminal",
    "Entertainer",
    "Folk Hero",
    "Guild Artisan",
    "Hermit",
    "Noble",
    "Outlander",
    "Sage",
    "Sailor",
    "Soldier",
    "Urchin",
  ],
  alignments: [
    "Lawful Good",
    "Neutral Good",
    "Chaotic Good",
    "Lawful Neutral",
    "True Neutral",
    "Chaotic Neutral",
    "Lawful Evil",
    "Neutral Evil",
    "Chaotic Evil",
  ],
  stats: ["Strength", "Dexterity", "Constitution", "Intelligence", "Wisdom", "Charisma"],
  statKeys: ["strength", "dexterity", "constitution", "intelligence", "wisdom", "charisma"],
};

export const cyberpunkRedData = {
  roles: [
    "Rockerboy",
    "Solo",
    "Netrunner",
    "Tech",
    "Medtech",
    "Media",
    "Exec",
    "Lawman",
    "Fixer",
    "Nomad",
  ],
  roleDescriptions: {
    Rockerboy: "Rebel rocker who uses music and charisma to fight authority",
    Solo: "Hired gun, bodyguard, or assassin",
    Netrunner: "Hacker who interfaces directly with the Net",
    Tech: "Inventor, builder, and gadget maker",
    Medtech: "Street doctor or trauma team medic",
    Media: "Reporter who exposes truth and corruption",
    Exec: "Corporate leader with money and connections",
    Lawman: "Cop or federal agent keeping the streets safe",
    Fixer: "Deal-maker, smuggler, information broker",
    Nomad: "Road warrior and family clan member",
  },
  culturalOrigins: [
    "North American",
    "South/Central American",
    "Western European",
    "Eastern European",
    "Middle Eastern/North African",
    "Sub-Saharan African",
    "South Asian",
    "South East Asian",
    "East Asian",
    "Oceania/Pacific Islander",
  ],
  personalityTraits: [
    "Shy and secretive",
    "Rebellious, antisocial, and violent",
    "Arrogant, proud, and aloof",
    "Moody, rash, and headstrong",
    "Picky, fussy, and nervous",
    "Stable and serious",
    "Silly and fluff-headed",
    "Sneaky and deceptive",
    "Intellectual and detached",
    "Friendly and outgoing",
  ],
  clothingStyles: [
    "Generic Chic",
    "Leisurewear",
    "Urban Flash",
    "Businesswear",
    "High Fashion",
    "Bohemian",
    "Bag Lady Chic",
    "Gang Colors",
    "Nomad Leathers",
    "Asia Pop",
  ],
  hairstyles: [
    "Mohawk",
    "Long and ratty",
    "Short and spiked",
    "Wild and all over",
    "Bald",
    "Striped",
    "Tinted",
    "Neat and short",
    "Short and curly",
    "Long and straight",
  ],
  valuedPerson: [
    "A parent",
    "A brother or sister",
    "A lover",
    "A friend",
    "Yourself",
    "A pet",
    "A teacher or mentor",
    "A public figure",
    "A personal hero",
    "No one",
  ],
  valuedMost: [
    "Money",
    "Honor",
    "Your word",
    "Honesty",
    "Knowledge",
    "Vengeance",
    "Love",
    "Power",
    "Family",
    "Friendship",
  ],
  feelingsAboutPeople: [
    "I stay neutral",
    "I like almost everyone",
    "I hate almost everyone",
    "People are tools to use",
    "Every person is worthwhile",
    "People are obstacles",
    "People are untrustworthy",
    "Wipe'em all out and start over",
    "People are wonderful!",
    "I'm a loner",
  ],
  stats: ["INT", "REF", "DEX", "TECH", "COOL", "WILL", "LUCK", "MOVE", "BODY", "EMP"],
  statKeys: ["int", "ref", "dex", "tech", "cool", "will", "luck", "move", "body", "emp"],
  statDescriptions: {
    INT: "Intelligence - Problem solving ability",
    REF: "Reflexes - Reaction speed and coordination",
    DEX: "Dexterity - Agility and fine motor control",
    TECH: "Technical Ability - Mechanical and technical aptitude",
    COOL: "Cool - Willpower and ability to stay calm",
    WILL: "Willpower - Mental strength and resistance",
    LUCK: "Luck - Fate points for clutch moments",
    MOVE: "Movement - Speed and mobility",
    BODY: "Body - Physical strength and toughness",
    EMP: "Empathy - Social skills and humanity",
  },
};

export type GameSystemType = "dnd" | "cyberpunk";
