-- NOTE: Column `password_hash` is now managed by Drizzle ORM via shared/schema.ts.
-- This file is kept for historical reference only.
--
-- The project uses Drizzle ORM with drizzle-kit for schema management.
-- The rooms.password_hash column is defined in shared/schema.ts (line 111).
--
-- To apply schema changes, use the official Drizzle workflow:
--   npm run db:push (development)
--   npm run db:migrate-prod (production)
--
-- These commands run drizzle-kit push which syncs the schema from shared/schema.ts
-- directly to the database. Manual SQL migrations are not used in this project.
